### ISSUE TITLE
Duplicate values

### ISSUE THREAD

**Issue by chrzyki** [lexibank/allenbai#14]
The following values exist twice, respectively:

* Eryuan_0075-0020-0065_m
* Eryuan_0075-0020-0065_n
* Yunlong_0073_i
* Jianchuan_0074-0073-02b0_i

**Comment by LinguList** [comment]
Where do they exist twice? Do we talk about phoneme inventories?

**Comment by chrzyki** [comment]
Values was indeed ambiguous here, pardon. Values as in *values*: https://github.com/lexibank/allenbai/blob/master/cldf/values.csv.

**Comment by LinguList** [comment]
But are they duplicate-duplicate? Because there's also the context which 
we distinguish for the values in the phoneme inventory (that's what the 
values reflect here).

**Comment by chrzyki** [comment]
Yes, as far as I can tell they're indeed duplicate-duplicate.

**Comment by LinguList** [comment]
can you trace the error and fix this, or should I do so? for lexibank, 
this is not important, maybe I accidentally listed them twice in our 
phoneme inventories.

**Comment by chrzyki** [comment]
I'll have a look and ask for help in case I can't find the cause.
