### ISSUE TITLE
first release for CLICS

### ISSUE THREAD

**Issue by LinguList** [lexibank/allenbai#2]

**Comment by xrotwang** [comment]
ok, will check. We could still use v1.0 as version specifier, but have "CLICS 2.0" as release title?

Alternatively, we could assign a git tag "clics2.0" to the release v1.0.

**Comment by xrotwang** [comment]
Ok, I elevated your privileges to "admin" now. Let me know if releasing works. We should have a policy on version specifiers, though. I'd advocate v1.0 style - and add additional tags as - well - tags :)

**Comment by LinguList** [comment]
CLICS 2.0 as rlease title is fine!

**Comment by LinguList** [comment]
the error was that the tag-settings were changed in github. I hope my releases of this and the sinitic dataset are okay in this way.

**Comment by xrotwang** [comment]
Adding tags to releases is really simple. See https://github.com/clld/clldutils/tags
The "testtag" was created by
```
git checkout tags/v2.1.0
git tag -a testtag
git push origin --tags
```
So we can add any number of tags to the "proper" version numbers.

**Comment by xrotwang** [comment]
Ah! It just occurred to me that we wanted to release after the corresponding pylexibank is released (and after adjusting the pylexibank version in the dataset's `setup.py`). So I guess we are in for some bugfix releases :)
